name: ExyliaHoppers
version: '1.0.0'
main: net.exylia.exyliaHoppers.ExyliaHoppers
api-version: '1.18'
authors: [ DiGround ]
description: If you need help, join to my discord.
website: https://link.exylia.net/@services
libraries:
  - 'net.kyori:adventure-platform-bukkit:4.3.4'
  - 'com.github.ben-manes.caffeine:caffeine:3.2.2'
  - 'com.google.inject:guice:7.0.0'
  - 'io.github.revxrsal:lamp.common:4.0.0-rc.14'
  - 'io.github.revxrsal:lamp.bukkit:4.0.0-rc.14'
  - 'io.github.revxrsal:lamp.brigadier:4.0.0-rc.14'